services:
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: statustracker4
      POSTGRES_PASSWORD: password
    volumes:
      - "pgdata:/var/lib/postgresql"
    ports:
      - "5432:5432"

volumes:
  pgdata:
